'''
총 N개의 문자열로 이루어진 집합 S가 주어진다.

입력으로 주어지는 M개의 문자열 중에서 
집합 S에 포함되어 있는 것이 총 몇 개인지 구하는 프로그램을 작성하시오.
'''
import sys
import heapq

# 내가푼거.. 936걸림 시간초과일듯 ;;
def 문자열집합():
  n , m = map(int, input().split())

  # 집합 s에 포함되는 문자열들
  s = dict()
  for i in range(n):
    s[input()]= i

  count = 0
  # 검사해야하는 문자열들
  for _ in range(m):
    if input() in s:
      count+=1

  print(count)

# 시간 132ms..
def 문자열집합2():
  N, M = map(int, input().split())
  a = sys.stdin.read().split()
  s, q = set(a[:N]), a[N:]
  print(sum(1 for x in q if x in s))


if __name__ == "__main__":
  문자열집합()